### ISSUE TITLE
노트 가이드 이미지

### ISSUE THREAD

**Issue by h-spear** [algo-plus/algo-plus#1]
![노트가이드1](https://github.com/algo-plus/algo-plus/assets/80024307/f181c319-3883-4591-ac67-aa7629638e1b)
![노트가이드2](https://github.com/algo-plus/algo-plus/assets/80024307/a4819990-2c38-4406-a78f-d47ac4191914)
![노트가이드3](https://github.com/algo-plus/algo-plus/assets/80024307/6f52fc9d-3a8e-4852-96f1-9721a47cd194)

**Comment by paul-lee-dev** [comment]
노트 가이드 이미지 임베드 완료
