### ISSUE TITLE
테스트케이스 출력문 버그

### ISSUE THREAD

**Issue by paul-lee-dev** [algo-plus/algo-plus#41]
**버그 설명 / Describe the bug**
- 테스트케이스 출력 시 출력이 초과될 때 페이지가 안뜨는 버그

**예상 문제 / Expected behavior**
- 문제 풀다 페이지가 안떠 불편함을 초래함

**Comment by sw-jelly** [comment]
Jdoodle API로 전환 후 출력초과를 표시할 수 있게 되었으므로 이 이슈를 닫습니다.
